/**
 * The library version this docs site documents.
 *
 * This is synced from packages/core/package.json in the library repo via
 * the sync-version.mjs script. When the library version changes, re-run:
 *   node scripts/sync-version.mjs
 *
 * DO NOT edit this file manually — it's auto-generated.
 */
export const LIBRARY_VERSION = '1.9.53';
